### ISSUE TITLE
Replace `@marshallofsound/webpack-asset-relocator-loader` to `@vercel/webpack-asset-relocator-loader`

### ISSUE THREAD

**Issue by cangSDARM** [Leopold-V/Reactirator#31]
**Describe the bug**
`@marshallofsound/webpack-asset-relocator-loader` is not an official package, and it seems to have certain risks ([its repo link on npmjs.com is not its repo](https://www.npmjser`.com/package/@marshallofsound/webpack-asset-relocator-loader))

used in: https://github.com/Leopold-V/Reactirator/blob/735f080036b4951fbc7db3b09232eb80b7d5baf3/webpack.rules.js#L11

So I suggest switching the related dependencies to `@vercel/webpack-asset-relocator-loader`, which is also the official package of vercel

**Comment by Leopold-V** [comment]
Hi, thanks for the information, I will have a look at this.

**Comment by Leopold-V** [comment]
#51
