### ISSUE TITLE
Component extension is wrong for Typescript projects

### ISSUE THREAD

**Issue by Leopold-V** [Leopold-V/Reactirator#42]
**Describe the bug**
In the manager part, the creation of new components result in a "jsx" component for Typescript project instead of "tsx".

**To Reproduce**
Go to the manager part and select a Typescript project, in the component page, generate a component, open your project and see your new component file extension.

**Expected behavior**
For Typescript project, component extension should be "tsx".

**Comment by JorgeOchoaReyes** [comment]
This issues seems to fixed, I cannot reproduce it. 

Step by step attempt: 

1. Created a ts CRA project using the creator 

2. Opened project in the manager 

3. Went to route components

4. Created a component called "test" using rfc mode 

5. Results are a file "test.tsx"

Let me know if I missed something, would love to help work on this project!

**Comment by Leopold-V** [comment]
Thanks a lot for testing. I tried again and I had the problem when I load a project bootstraped with vite or Next.js, but it is indeed working with CRA!
After further investigation the reason is that the "istypescript" value from the store isn't correct:
https://i.gyazo.com/58afbdb2a8c9b2d6f978e32e5520d193.png

Thats because we're detecting typescript from the "dependencies" section of the package.json:
```js
              dispatch(
                initProject({
                  projectName: contentObj.name,
                  projectPath: filepath[0],
                  starter: starter,
                  scriptDev: scriptDev,
                  isTypescript: contentObj.dependencies.typescript ? true : false,
                })
              );
```
While we should check for the dev dependencies I guess.
