### ISSUE TITLE
Backslash causing errors in Mac OS file paths. 

### ISSUE THREAD

**Issue by JorgeOchoaReyes** [Leopold-V/Reactirator#46]
**Describe the bug**
Files paths with backslashes ("\\") causes errors in mac platform.

**To Reproduce**
1. Must be in mac os to reproduce, using a bash terminal. 
2. Create any project, vite or CRA. 
3. Input valid name 
4. All other fields are optional. 
5. Install.

**Expected behavior**
Expected behavior is that the project would be created with specified folders and paths. 

**Screenshots**
<img width="1439" alt="Screenshot 2023-02-10 at 5 33 14 PM" src="https://user-images.githubusercontent.com/60721681/218228559-ae213565-d387-4828-92e8-be6ede94d9da.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.1

**Additional context**

**Comment by Leopold-V** [comment]
Hey, good catch!
I merge #47 , thank you for your first contribution on Reactirator. Any help like this is very appreciated.
