### ISSUE TITLE
Features file or roadmap 

### ISSUE THREAD

**Issue by JorgeOchoaReyes** [Leopold-V/Reactirator#50]
Would be great to have some file that has features that are in progress or planned to be added for the project. I remember there was one a long time ago when I first found this project, but I do not see it anymore. 

There are some interesting templates that could be added to this project like for example adding the [t3-app with trpc](https://github.com/t3-oss/create-t3-app), or a setup with [firebase and trpc](https://github.com/JorgeOchoaReyes/trpc-firebase) that in the components page lets you set up cron jobs files, or function triggers.

**Comment by Leopold-V** [comment]
Hi, are you talking about the [project](https://github.com/Leopold-V/Reactirator/projects?type=classic) section ?
At this moment there is only the [upcoming-features](https://github.com/Leopold-V/Reactirator#upcoming-features) (where for example being able to pick a specific template is mentionned!) but for sure having a proper roadmap is important and I can work on this very soon.
